#! /bin/bash

for jj in "$@";do
    name=$( echo $jj | cut --delimiter="." -f 1 | sed s/-/_/g ).m
    printf " %s\n" $name
    printf "%% %s\n" $name > $name
    echo   "%  QUADRUPOLOS" >> $name
    echo   "%  ===========" >> $name

    quad=($( cat $jj | grep KQUAD | cut --delimiter=":" -f 1 | tr '[:upper:]' '[:lower:]' | se$
    quad_str=($( cat $jj | grep KQUAD | cut --delimiter="=" -f 3 | cut --delimiter="," -f 1 ))

    for ii in $(seq 0 $((${#quad[*]}-1)));do
       	printf "${quad[ii]}\t= ${quad_str[ii]};\n" >> $name
    done

    echo " " >> $name
    echo "%  SEXTUPOLOS" >> $name
    echo "%  ===========" >> $name


    sext=($( cat $jj | grep KSEXT | cut --delimiter=":" -f 1 | tr '[:upper:]' '[:lower:]' | se$
    sext_str=($( cat $jj | grep KSEXT | cut --delimiter="=" -f 3 | cut --delimiter="," -f 1 | $

    for ii in $(seq 0 $((${#sext[*]}-1)));do
       	printf "${sext[ii]}\t= ${sext_str[ii]};\n" >> $name
    done

    printf "\n" >> $name
done
