#!/bin/bash

# git status all repositories
# $FACCODE should be sourced from ~/.bashrc -> scripts/bashrc 

cd $FACCODE/collective_effects && git status
cd $FACCODE/fieldmaptrack && git status
cd $FACCODE/job_manager && git status
cd $FACCODE/lnls && git status
cd $FACCODE/mathphys && git status
cd $FACCODE/MatlabMiddleLayer && git status
cd $FACCODE/pyaccel && git status
cd $FACCODE/scripts && git status
cd $FACCODE/sirius && git status
cd $FACCODE/sirius_wiki && git status
cd $FACCODE/tools && git status
cd $FACCODE/trackcpp && git status
cd $FACCODE/tracy_sirius && git status
cd $FACCODE/va && git status
