#!/bin/bash

# Clone repositories moved from code
#
# Run this script at the code level.

git clone ssh://git@github.com/lnls-fac/collective_effects.git code/collective_effects
git clone ssh://git@github.com/lnls-fac/fieldmaptrack.git code/fieldmaptrack
git clone ssh://git@github.com/lnls-fac/job_manager.git code/job_manager
git clone ssh://git@github.com/lnls-fac/lnls.git code/lnls
git clone ssh://git@github.com/lnls-fac/mathphys.git code/mathphys
git clone ssh://git@github.com/lnls-fac/MatlabMiddleLayer.git code/MatlabMiddleLayer
git clone ssh://git@github.com/lnls-fac/pyaccel.git code/pyaccel
git clone ssh://git@github.com/lnls-fac/scripts.git code/scripts
git clone ssh://git@github.com/lnls-fac/sirius.git code/sirius
git clone ssh://git@github.com/lnls-fac/sirius_wiki.git code/sirius_wiki
git clone ssh://git@github.com/lnls-fac/tools.git code/tools
git clone ssh://git@github.com/lnls-fac/trackcpp.git code/trackcpp
git clone ssh://git@github.com/lnls-fac/tracy_sirius.git code/tracy_sirius
git clone ssh://git@github.com/lnls-fac/va.git code/va
